//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAuction.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelAuction.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ja&quot;&gt;
        ///&lt;head&gt;
        ///
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;title&gt;ヤフオク!&lt;/title&gt;
        ///&lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot;&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///&lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;https://s.yimg.jp/images/auc/pc/common/css/buyerdetail/1.0.1/standard_common_min.css&quot; type=&quot;text/css&quot; media=&quot;all&quot;&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;https://s.yimg.jp/images/auc/pc/buyerdetail/css/1.0.4/style_common_min.css&quot; type=&quot;text/css&quot; media=&quot;all&quot;&gt;
        ///&lt;link rel=&quot;st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string htmltemplate {
            get {
                return ResourceManager.GetString("htmltemplate", resourceCulture);
            }
        }
    }
}
